export { default as Navbar } from "./Navbar";
export { default as Hero } from "./Hero";
export { default as Features } from "./Features";
export { default as HowItWorks } from "./HowItWorks";
export { default as UserTypes } from "./UserTypes";
export { default as Stats } from "./Stats";
export { default as CTA } from "./CTA";
export { default as Footer } from "./Footer";
export { default as PhoneShowcase } from "./PhoneShowcase";
